# Generated by Django 4.1.4 on 2022-12-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('question', models.TextField(primary_key=True, serialize=False, unique=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос, ответ',
                'verbose_name_plural': 'Вопроросы, ответы',
            },
        ),
    ]
