# Generated by Django 4.1.4 on 2022-12-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatState',
            fields=[
                ('chat_id', models.TextField(primary_key=True, serialize=False, unique=True, verbose_name='Имя пользователя в телеграм')),
                ('state', models.IntegerField(verbose_name='Состояние')),
            ],
            options={
                'verbose_name': ('Состояние для бота',),
                'verbose_name_plural': 'Состояния для бота',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('question', models.TextField(primary_key=True, serialize=False, unique=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('is_active', models.BooleanField(default=False, verbose_name='Доступно?')),
            ],
            options={
                'verbose_name': 'Вопрос, ответ',
                'verbose_name_plural': 'Вопроросы, ответы',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст заявки')),
                ('photo', models.FileField(upload_to='media/', verbose_name='Изображение')),
                ('auditory', models.TextField(verbose_name='Целевая аудитория')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('from_user', models.TextField(default='telegram', verbose_name='От кого')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.TextField(unique=True, verbose_name='Чат id пользователя')),
                ('username', models.TextField(unique=True, verbose_name='Username telegram')),
                ('name', models.TextField(verbose_name='Имя пользователя telegram')),
                ('avatar', models.FileField(default='usericon.png', upload_to='media/', verbose_name='Аватар пользователя в телеграм')),
                ('messages', models.ManyToManyField(blank=True, to='bot.message', verbose_name='Сообщения')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
    ]
