# Generated by Django 4.1.4 on 2022-12-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatState',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False, unique=True, verbose_name='Имя пользователя в телеграм')),
                ('state', models.IntegerField(verbose_name='Состояние')),
            ],
        ),
    ]
