# Generated by Django 4.1.4 on 2022-12-10 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 11, 0, 56, 49, 327394), verbose_name='Время отправки'),
        ),
    ]
