# Generated by Django 4.1.4 on 2022-12-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_chatstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст рассылки')),
                ('photo', models.FileField(upload_to='', verbose_name='Изображение')),
                ('auditory', models.TextField(verbose_name='Целевая аудитория')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.AlterModelOptions(
            name='chatstate',
            options={'verbose_name': ('Состояние для бота',), 'verbose_name_plural': 'Состояния для бота'},
        ),
        migrations.RenameField(
            model_name='chatstate',
            old_name='username',
            new_name='chat_id',
        ),
    ]
