# Generated by Django 4.1.4 on 2022-12-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_mail_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Доступно?'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='photo',
            field=models.FileField(upload_to='media/', verbose_name='Изображение'),
        ),
    ]
