# Generated by Django 4.1.4 on 2022-12-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_faq_is_active_alter_mail_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='mail',
            name='text',
            field=models.TextField(verbose_name='Текст заявки'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.TextField(verbose_name='Чат id пользователя')),
                ('username', models.TextField(verbose_name='Username telegram')),
                ('name', models.TextField(verbose_name='Имя пользователя telegram')),
                ('messages', models.ManyToManyField(blank=True, to='bot.message', verbose_name='Сообщения в чате')),
            ],
        ),
    ]
