# Generated by Django 4.1.4 on 2022-12-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_message_alter_mail_options_alter_mail_text_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
