# Generated by Django 4.1.4 on 2022-12-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_chat_messages_chat_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bot.message', verbose_name='Сообщения'),
        ),
    ]
