# Generated by Django 4.1.4 on 2022-12-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_remove_chat_messages_chat_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.chat', verbose_name='Сообщения'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='telegram_chat_id',
            field=models.TextField(unique=True, verbose_name='Чат id пользователя'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.TextField(unique=True, verbose_name='Username telegram'),
        ),
    ]
