# Generated by Django 4.1.4 on 2022-12-09 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_remove_chat_messages_message_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.message', verbose_name='Сообщения'),
        ),
    ]
