# Generated by Django 4.1.4 on 2022-12-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_remove_chat_messages_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.FileField(default='media/usericon.png', upload_to='media/', verbose_name='Аватар пользователя в телеграм'),
        ),
    ]
